---
title: "Model 3 Neg Binom"
author: "Ben Moolman, Craig Orman, Ethan Pross"
output: pdf_document
---


```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyverse)
library(knitr)
library(ggplot2)
library(coda)
```

## Beginning Data preparing

```{r, warning = FALSE, message = FALSE, echo = FALSE}
original_tbl <- read.csv("./NBA-BoxScores-2023-2024.csv")


original_tbl <- mutate(original_tbl,
                       START_POSITION = na_if(START_POSITION, ""),
                       START_POSITION = factor(original_tbl$START_POSITION),
                       COMMENT = na_if(COMMENT, ""),
                       COMMENT = factor(original_tbl$COMMENT),
                       MIN = na_if(MIN, ""),
                       MIN = str_replace(MIN, "([0-9]+)\\.[0-9]+:", "\\1:"),
                       )

starting_dat = original_tbl[original_tbl$START_POSITION != "",]
lebron_vs_steph_games = c(22300650, 22300973, 22301155)

# Code to add in opposing team

game_registry <- distinct(starting_dat[,c(2,3, 4)]) %>%
  group_by(GAME_ID) %>%
  arrange(TEAM_ID, .by_group = TRUE) %>%
  mutate(slot = paste0("TEAM", row_number())) %>%
  pivot_wider(
    names_from = slot,
    values_from = c(TEAM_ID, TEAM_ABBREVIATION),
    names_sep = "_"
  )

colnames(game_registry) <- c("Game_ID", "Team_1_ID", "Team_2_ID", "Team_1_Abbrev", "Team_2_Abbrev")


starting_dat$Opposing_Team_Name_ID = NA
starting_dat$Opposing_Team_Name = NA

starting_dat <- starting_dat %>%
  left_join(game_registry, by = c("GAME_ID" = "Game_ID")) %>%
  mutate(
    Opposing_Team_Name_ID = if_else(
      TEAM_ID == Team_1_ID, Team_2_ID,
      if_else(TEAM_ID == Team_2_ID, Team_1_ID, NA_integer_)
    ),
    Opposing_Team_Name = if_else(
      TEAM_ID == Team_1_ID, Team_2_Abbrev,
      if_else(TEAM_ID == Team_2_ID, Team_1_Abbrev, NA_character_)
    )
  ) %>%
  select(-Team_1_ID, -Team_2_ID, -Team_1_Abbrev, -Team_2_Abbrev)

```

```{r, warning=FALSE}
## Ben's DRTG code!
# Calculate total points per team per game
# here, datatest2 is the entire data frame that is not filtered for starters
# filtering dataset to remove NAs which arise a player doesnt record any minutes in the game (sitting out)
team_points <- na.omit(original_tbl) %>%
  group_by(GAME_ID, TEAM_ID) %>%
  summarize(TeamPoints = sum(PTS), .groups = "drop")

# 
team_points_opponent <- team_points %>%
  rename(OPP_TEAM_ID = TEAM_ID, OpponentPoints = TeamPoints)

# join and filter
team_vs_opponent <- team_points %>%
  inner_join(team_points_opponent, by = "GAME_ID") %>%
  filter(TEAM_ID != OPP_TEAM_ID)

# calculate average opponent points per team (our DRTG)
team_drtg <- team_vs_opponent %>%
  group_by(TEAM_ID) %>%
  summarize(DRTG_proxy = mean(OpponentPoints), n_games = n(), .groups = "drop")

range(team_drtg$DRTG_proxy)
mean(team_drtg$DRTG_proxy)
```
DRTG data being joined to the starting data

```{r, warning=FALSE}
## NOW ADDING DRTG vars to original_tbl


# Each team plays one opponent per game, so we pair them like this:
game_team_pairs <- original_tbl %>%
  select(GAME_ID, TEAM_ID) %>%
  distinct()

# Join to get each game twice: once for each team, with their opponent
opponent_map <- game_team_pairs %>%
  inner_join(game_team_pairs, by = "GAME_ID") %>%
  filter(TEAM_ID.x != TEAM_ID.y) %>%
  rename(TEAM_ID = TEAM_ID.x, OPP_TEAM_ID = TEAM_ID.y)

# Add opponent DRTG to the mapping
opponent_map <- opponent_map %>%
  left_join(team_drtg %>% rename(OPP_TEAM_ID = TEAM_ID, OPP_DRTG = DRTG_proxy),
            by = "OPP_TEAM_ID")

# Join to add opponent DRTG column to the full data
starting_dat <- starting_dat %>%
  left_join(opponent_map, by = c("GAME_ID", "TEAM_ID"))

mean_drtg <- mean(team_drtg$DRTG_proxy)
starting_dat <- starting_dat %>%
  mutate(centered_OPP_DRTG = OPP_DRTG - mean_drtg)
```

## Model 3 implementation

$$
\begin{aligned}
  y_{ikj} &\sim Binom(n_{ikj}, p_{ik})\\
  p_{ik} &\sim \phi \times Beta(5,5)\\
  n_{ijk} &\sim Neg Binom(r,\theta)\\
  p(r, \theta) &\varpropto \sqrt{\frac{r_i}{\theta^2}(1-\theta_i)} &\text{ Jeffreys prior}\\
\end{aligned}
$$

Next we write out the full conditionals
$$
\begin{aligned}
  y_{ikj}|... &\sim Bin(n_{ikj},p_{ik})\\
  p_{ik}|... &\varpropto \phi p(y|p_{ik},n_{ikj})p(p_{ik}|a,b)\\
  &\varpropto \min(1, Beta(\sum(y)+5,N-\sum(y)+5\\
  n_{ikj}|... &\varpropto p(y_{ikj}|p_{ik},n_{ikj})p(n_{ikj}|r,\theta)\\
  &\varpropto \ln\left( \prod_{j,k} (n_{ijk} + r_i - 1)! \right) 
- \ln\left( \prod_{j,k} (n_{ijk} - y_{ijk})! \right) 
+ \ln\left( \prod_{j,k} \left[ (1 - \theta_i)(1 - p_{ik}) \right]^{n_{ijk}} \right)\\
p(r_i|...) &\varpropto p(n_ijk|r_i, \theta_i)p(r_i, \theta_i)\\
&\varpropto \ln(\prod_{j,k}[(n_{ijk}+r_i-1)!]-\ln(\prod_{j,k}[(r_i-1)!]) + \ln(\prod_{j,k}[(\theta_i^{r_i})!])+\ln(r_i^{\frac12})\\
p(\theta_i) &\varpropto p(n_ijk|r_i, \theta_i)p(r_i, \theta_i)\\
&\sim Beta(\sum_{j,k}n_{ijk} + \frac12, r_i - 1)
  \end{aligned}
$$

So for this, we kinda have a full thingy set up?

```{r}
# Data and prior
# 2544 is Lebron's player id 
# 1610612744 is GSw, Steph Curry's team

log_n_func = function(n, r, y, theta, p){
  sum(log(factorial(n+r-1)))- sum(log(factorial(n-y))) + sum(n)*log(1-theta) +sum(n) * log(1-p)
}

log_r_func = function(r, n, y, theta, p) {
  sum(log(factorial(n+r-1)))-sum(log(factorial(r-1)))+sum(r*log(theta))+log(r)/2
}

#### RESETING COMMANDS START

data = starting_dat
inits=list(n = 24,
           r = 20,
           theta = 0.3)
prop_sd = list(n = 0.1, r = 0.4)
psi = 0.01
player_id = 2544 # LeBron
opp_team_id = 1610612744 #GSW
n_iter = 100

### RESETTING COMMANDS END

gibby = function(data, inits, prop_sd, psi, player_id, opp_team_id, n_iter=5000, n_burnin = 1) {
  # Gather true data
  player_dat = data[data$PLAYER_ID == player_id, ]
  player_dat = player_dat[player_dat$Opposing_Team_Name_ID == opp_team_id, ]
  true_y = player_dat$FGM
  true_n = player_dat$FGA
  DRTG_var = data$centered_OPP_DRTG[1]
  
  # initial value setup
  p = inits$p
  n = inits$n
  r = inits$r
  theta = inits$theta
  
  # Save structure (REVIEW)
  n_keep = numeric(n_iter)
  p_keep = numeric(n_iter)
  r_keep = numeric(n_iter)
  theta_keep = numeric(n_iter)
  
  # Proposal variances (TODO)
  prop_n_sd = prop_sd$n
  prop_r_sd = prop_sd$r
  
  # Gibbs sampler main
  for (i in 1:n_iter) {
    # Generate p
    pi = rbeta(1,5+sum(true_y), 5+sum(n - true_y))
    p = min(1, pi * exp(psi * DRTG_var))
    
    # Generate n
    prop_n = rnorm(1, mean=n, sd = prop_n_sd) # round to ensure its integer, using r as thats what Dr. Niemi did 
    logn = log_n_func(n=prop_n, r, true_y, theta, p) - log_n_func(n=n, r, true_y, theta, p)
    if (is.finite(logn) && log(runif(1)) < logn) {
      n <- prop_n
    }
    
    # generate r 
    prop_r = rnorm(1, mean=r, sd = prop_r_sd) # round to ensure its integer, using r as thats what Dr. Niemi did 
    logr = log_r_func(prop_r, n, true_y, theta, p) - log_r_func(r, n, true_y, theta, p)
    if (is.finite(logr) && log(runif(1)) < logr) {
      r <- prop_r
    }
    # generate theta
    theta = rbeta(1, (sum(n)+ (1/2)), (r - 1))
    
    # Save values 
    
    n_keep[i] =n
    p_keep[i] = p 
    r_keep[i] = r
    theta_keep[i] = theta
  }
  output = list(n = n_keep[n_burnin:n_iter], p = p_keep[n_burnin:n_iter],
                r = r_keep[n_burnin:n_iter], theta = theta_keep[n_burnin:n_iter])
  return(output)
}

```

```{r}

# 2544 is Lebron's player id 
# 1610612744 is GSw, Steph Curry's team

true_dat = starting_dat[starting_dat$PLAYER_ID == 2544,]
true_dat = true_dat[true_dat$Opposing_Team_Name_ID == 1610612744,]

#function(data, inits, prop_sd, psi, player_id, opp_team_id, n_iter=5000)
inits=list(n = true_dat$FGA,
           r = 20,
           theta = 0.5)
prop_sd = list(n = 100, r = 2)
n_iter = 26000
n_burnin = 1000
output = suppressWarnings(gibby(starting_dat, inits, prop_sd = prop_sd,
                                psi=0.01, player_id = 2544, opp_team_id = 1610612744,
                                n_iter=n_iter, n_burnin = n_burnin))
# Diagnostics
plot(y=output$n, x = 1:length(output$n), type = 'l', main="Trace Plot of n")
# plot(as.mcmc(output$n), main="n")
abline(h = mean(output$n), col='red', lwd=2)
abline(h = mean(true_dat$FGA), col='blue', lwd=2)

plot(y=output$p, x = 1:length(output$n), type = 'l', main="Trace Plot of p")
abline(h = mean(output$p), col='red', lwd=2)
abline(h = mean(true_dat$FG_PCT), col='blue', lwd=2)

plot(y=output$r, x = 1:length(output$n), type = 'l', main="Trace Plot of r")
abline(h = mean(output$r), col='red', lwd=2)
plot(y=output$theta, x = 1:length(output$n), type = 'l', main="Trace Plot of theta")
abline(h = mean(output$theta), col='red', lwd=2)
```


OLD GIBBY
```{r}
gibby = function(data, inits, prop_sd, psi, player_id, opp_team_id, n_iter=5000, n_burnin = 1) {
  # Gather true data
  player_dat = data[data$PLAYER_ID == player_id, ]
  player_dat = player_dat[player_dat$Opposing_Team_Name_ID == opp_team_id, ]
  true_y = player_dat$FGM
  true_n = player_dat$FGA
  DRTG_var = data$centered_OPP_DRTG[1]
  
  # initial value setup
  p = inits$p
  n = inits$n
  r = inits$r
  theta = inits$theta
  
  # Save structure (REVIEW)
  n_keep = numeric(n_iter)
  p_keep = numeric(n_iter)
  r_keep = numeric(n_iter)
  theta_keep = numeric(n_iter)
  
  # Proposal variances (TODO)
  prop_n_sd = prop_sd$n
  prop_r_sd = prop_sd$r
  
  # Gibbs sampler main
  for (i in 1:n_iter) {
    # Generate p
    pi = rbeta(1,5+sum(true_y), 5+sum(n - true_y))
    p = min(1, pi * exp(psi * DRTG_var))
    
    # Generate n
    prop_n = round(rnorm(1, mean=n, sd = prop_n_sd)) # round to ensure its integer, using r as thats what Dr. Niemi did 
    logn = log_n_func(n=prop_n, r, true_y, theta, p) - log_n_func(n=n, r, true_y, theta, p)
    if (is.finite(logn) && log(runif(1)) < logn) {
      n <- prop_n
    }
    
    # generate r 
    prop_r = round(rnorm(1, mean=r, sd = prop_r_sd)) # round to ensure its integer, using r as thats what Dr. Niemi did 
    logr = log_r_func(prop_r, n, true_y, theta, p) - log_r_func(r, n, true_y, theta, p)
    if (is.finite(logr) && log(runif(1)) < logr) {
      r <- prop_r
    }
    # generate theta
    theta = rbeta(1, (sum(n)+ (1/2)), (r - 1))
    
    # Save values 
    
    n_keep[i] =n
    p_keep[i] = p 
    r_keep[i] = r
    theta_keep[i] = theta
  }
  output = list(n = n_keep[n_burnin:n_iter], p = p_keep[n_burnin:n_iter],
                r = r_keep[n_burnin:n_iter], theta = theta_keep[n_burnin:n_iter])
  return(output)
}

inits=list(p = 0.7,
           n = 25,
           r = 25,
           theta = 0.5)
prop_sd = list(n = 0.5, r = 2)
n_iter = 11000
n_burnin = 1000
output = suppressWarnings(gibby(starting_dat, inits, prop_sd = prop_sd,
                                psi=0.1, player_id = 2544, opp_team_id = 1610612746,
                                n_iter=n_iter, n_burnin = n_burnin))

# Diagnostics
plot(y=output$n, x = 1:length(output$n), type = 'l', main="Trace Plot of n")
# plot(as.mcmc(output$n), main="n")
abline(h = mean(output$n), col='red', lwd=2)
abline(h = mean(true_dat$FGA), col='blue', lwd=2)

plot(y=output$p, x = 1:length(output$n), type = 'l', main="Trace Plot of p")
abline(h = mean(output$p), col='red', lwd=2)
abline(h = mean(true_dat$FG_PCT), col='blue', lwd=2)

plot(y=output$r, x = 1:length(output$n), type = 'l', main="Trace Plot of r")
abline(h = mean(output$r), col='red', lwd=2)
plot(y=output$theta, x = 1:length(output$n), type = 'l', main="Trace Plot of theta")
abline(h = mean(output$theta), col='red', lwd=2)
```


