---
title: "Model Proposal"
author: "Ben Moolman, Craig Orman, Ethan Pross"
output: pdf_document
---

```{r, echo=FALSE}
library(dplyr)
library(tidyverse)
library(knitr)
library(skimr)
library(tidyr)
library(ggplot2)
library(forcats)
```


```{r, warning = FALSE, message = FALSE, echo = FALSE}
original_tbl <- read.csv("../NBA-BoxScores-2023-2024.csv")
# original_tbl$COMMENT[original_tbl$COMMENT == ""] <- NA
# original_tbl$COMMENT <- factor(original_tbl$COMMENT)


original_tbl <- mutate(original_tbl,
                       START_POSITION = na_if(START_POSITION, ""),
                       START_POSITION = factor(original_tbl$START_POSITION),
                       COMMENT = na_if(COMMENT, ""),
                       COMMENT = factor(original_tbl$COMMENT),
                       MIN = na_if(MIN, ""),
                       MIN = str_replace(MIN, "([0-9]+)\\.[0-9]+:", "\\1:"),
                       
                       )


starting_dat = original_tbl[original_tbl$START_POSITION != "",]
lebron_vs_steph_games = c(22300650, 22300973, 22301155)

```

```{r}
# Calculate total points per team per game
# here, datatest2 is the entire data frame that is not filtered for starters
team_points <- starting_dat %>%
  group_by(GAME_ID, TEAM_ID) %>%
  summarize(TeamPoints = sum(PTS), .groups = "drop")

# tidying
team_points_opponent <- team_points %>%
  rename(OPP_TEAM_ID = TEAM_ID, OpponentPoints = TeamPoints)

# join and filter
team_vs_opponent <- team_points %>%
  inner_join(team_points_opponent, by = "GAME_ID") %>%
  filter(TEAM_ID != OPP_TEAM_ID)

# calculate average opponent points per team (our DRTG)
team_drtg <- team_vs_opponent %>%
  group_by(TEAM_ID) %>%
  summarize(DRTG_proxy = mean(OpponentPoints), n_games = n(), .groups = "drop")

range(team_drtg$DRTG_proxy)
mean(team_drtg$DRTG_proxy)
```


What I want is a scatter plot. Y is FGA, X is opposing team name, and each dot represents one of the games played against them.

```{r}
game_registry <- distinct(starting_dat[,c(2,3, 4)]) %>%
  group_by(GAME_ID) %>%
  arrange(TEAM_ID, .by_group = TRUE) %>%
  mutate(slot = paste0("TEAM", row_number())) %>%
  pivot_wider(
    names_from = slot,
    values_from = c(TEAM_ID, TEAM_ABBREVIATION),
    names_sep = "_"
  )

colnames(game_registry) <- c("Game_ID", "Team_1_ID", "Team_2_ID", "Team_1_Abbrev", "Team_2_Abbrev")


starting_dat$Opposing_Team_Name_ID = NA
starting_dat$Opposing_Team_Name = NA

starting_dat <- starting_dat %>%
  left_join(game_registry, by = c("GAME_ID" = "Game_ID")) %>%
  mutate(
    Opposing_Team_Name_ID = if_else(
      TEAM_ID == Team_1_ID, Team_2_ID,
      if_else(TEAM_ID == Team_2_ID, Team_1_ID, NA_integer_)
    ),
    Opposing_Team_Name = if_else(
      TEAM_ID == Team_1_ID, Team_2_Abbrev,
      if_else(TEAM_ID == Team_2_ID, Team_1_Abbrev, NA_character_)
    )
  ) %>%
  select(-Team_1_ID, -Team_2_ID, -Team_1_Abbrev, -Team_2_Abbrev)



lebron_dat = starting_dat[starting_dat$PLAYER_ID %in% 2544, ] # lebron 2544 and steph curry 201939 anthony davis (lebron teammate) 203076
anthony_dat = starting_dat[starting_dat$PLAYER_ID %in% 203076, ]
```

```{r, echo=FALSE, eval=FALSE}
# For loop of doom, but it works!
# for (i in 1:nrow(starting_dat)) {
#   for (j in 1:nrow(game_registry)) {
#     
#     if (starting_dat$GAME_ID[i] == game_registry$Game_ID[j]){
#       
#       if (starting_dat$TEAM_ID[i] == game_registry$Team_1_ID[j]) {
#         starting_dat$Opposing_Team_Name_ID[i] = game_registry$Team_2_ID[j]
#         starting_dat$Opposing_Team_Name[i] = game_registry$Team_2_Abbrev[j]
#       }
#       if (starting_dat$TEAM_ID[i] == game_registry$Team_2_ID[j]) {
#         starting_dat$Opposing_Team_Name_ID[i] = game_registry$Team_1_ID[j]
#         starting_dat$Opposing_Team_Name[i] = game_registry$Team_1_Abbrev[j]
#       }
#       
#     }
# 
#   }
# }
```

Examining FGA and FGM 

```{r}

team_ids = lebron_dat[lebron_dat$PLAYER_ID == 2544,c(2,3)]

hist(lebron_dat$FGA, main="Histogram of Lebron's FGA")

# hist(rpois(1000, 10))
```

```{r}

lebron_dat = starting_dat[starting_dat$PLAYER_ID %in% 2544, ] # lebron 2544 and steph curry 201939
lebron_dat <- lebron_dat %>%
  mutate(Opposing_Team_Name = fct_reorder(as.factor(Opposing_Team_Name), FGA, .fun = mean))
mean_fga = mean(lebron_dat$FGA)
sd_fga = sd(lebron_dat$FGA)

df_lines <- lebron_dat %>%
  group_by(Opposing_Team_Name) %>%
  arrange(FGA) %>%
  mutate(index = row_number())  # create a pseudo-x to keep line ordering

ggplot(df_lines, aes(x = FGA, y = Opposing_Team_Name, group = Opposing_Team_Name)) +
  geom_point(aes(x = Opposing_Team_Name, y = FGA)) +
  geom_line(aes(x = Opposing_Team_Name, y = FGA, group = Opposing_Team_Name), orientation = "FGA") +
  labs(
    title = "Lebron FGA group variation plot",
    subtitle = "Data is only for Lebron, includes mean in red and 1 sd in blue",
    x = "Opposing Team ID",
    y = "FGA"
  ) +
  geom_hline(yintercept = mean_fga, color = "red", linetype = "solid", size = 0.5) +
  geom_hline(yintercept = mean_fga - sd_fga, color = "blue", linetype = "dotted", size = 0.5) +
  geom_hline(yintercept = mean_fga + sd_fga, color = "blue", linetype = "dotted", size = 0.5)+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))

# And now for Steph
steph_dat = starting_dat[starting_dat$PLAYER_ID == 201939, ] # lebron 2544 and steph curry 201939

steph_dat$Opposing_Team_Name <- factor(steph_dat$Opposing_Team_Name, levels = levels(lebron_dat$Opposing_Team_Name))
mean_fga = mean(steph_dat$FGA)
sd_fga = sd(steph_dat$FGA)

df_lines <- steph_dat %>%
  group_by(Opposing_Team_Name) %>%
  arrange(FGA) %>%
  mutate(index = row_number())  # create a pseudo-x to keep line ordering

ggplot(df_lines, aes(x = FGA, y = Opposing_Team_Name, group = Opposing_Team_Name)) +
  geom_point(aes(x = Opposing_Team_Name, y = FGA)) +
  geom_line(aes(x = Opposing_Team_Name, y = FGA, group = Opposing_Team_Name), orientation = "FGA") +
  labs(
    title = "Steph Curry FGA group variation plot",
    subtitle = "Data is only for Steph Curry, includes mean in red and 1 sd in blue",
    x = "Opposing Team ID",
    y = "FGA"
  ) +
  geom_hline(yintercept = mean_fga, color = "red", linetype = "solid", size = 0.5) +
  geom_hline(yintercept = mean_fga - sd_fga, color = "blue", linetype = "dotted", size = 0.5) +
  geom_hline(yintercept = mean_fga + sd_fga, color = "blue", linetype = "dotted", size = 0.5)+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))
```

```{r}
library(ggplot2)
library(forcats)
library(forcats)

lebron_dat <- lebron_dat %>%
  mutate(Opposing_Team_Name = fct_reorder(as.factor(Opposing_Team_Name), FG_PCT, .fun = mean))
mean_fga = mean(lebron_dat$FG_PCT)
sd_fga = sd(lebron_dat$FG_PCT)

df_lines <- lebron_dat %>%
  group_by(Opposing_Team_Name) %>%
  arrange(FG_PCT) %>%
  mutate(index = row_number())  # create a pseudo-x to keep line ordering

ggplot(df_lines, aes(x = FG_PCT, y = Opposing_Team_Name, group = Opposing_Team_Name)) +
  geom_point(aes(x = Opposing_Team_Name, y = FG_PCT)) +
  geom_line(aes(x = Opposing_Team_Name, y = FG_PCT, group = Opposing_Team_Name), orientation = "FG_PCT") +
  labs(
    title = "Lebron FG_PCT group variation plot",
    subtitle = "Data is only for Lebron, includes mean in red and 1 sd in blue",
    x = "Opposing Team ID",
    y = "FG_PCT"
  ) +
  geom_hline(yintercept = mean_fga, color = "red", linetype = "solid", size = 0.5) +
  geom_hline(yintercept = mean_fga - sd_fga, color = "blue", linetype = "dotted", size = 0.5) +
  geom_hline(yintercept = mean_fga + sd_fga, color = "blue", linetype = "dotted", size = 0.5)
```

```{r}
library(ggplot2)
library(forcats)
library(forcats)

lebron_dat <- lebron_dat %>%
  mutate(Opposing_Team_Name = fct_reorder(as.factor(Opposing_Team_Name), FGM, .fun = mean))
mean_fga = mean(lebron_dat$FGM)
sd_fga = sd(lebron_dat$FGM)

df_lines <- lebron_dat %>%
  group_by(Opposing_Team_Name) %>%
  arrange(FGM) %>%
  mutate(index = row_number())  # create a pseudo-x to keep line ordering

ggplot(df_lines, aes(x = FGM, y = Opposing_Team_Name, group = Opposing_Team_Name)) +
  geom_point(aes(x = Opposing_Team_Name, y = FGM)) +
  geom_line(aes(x = Opposing_Team_Name, y = FGM, group = Opposing_Team_Name), orientation = "FGM") +
  labs(
    title = "Lebron FGM group variation plot",
    subtitle = "Data is only for Lebron, includes mean in red and 1 sd in blue",
    x = "Opposing Team ID",
    y = "FGM"
  ) +
  geom_hline(yintercept = mean_fga, color = "red", linetype = "solid", size = 0.5) +
  geom_hline(yintercept = mean_fga - sd_fga, color = "blue", linetype = "dotted", size = 0.5) +
  geom_hline(yintercept = mean_fga + sd_fga, color = "blue", linetype = "dotted", size = 0.5) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))
```


```{r}
par(mfrow=c(2,2))
hist(lebron_dat$FGA)
steph_dat = starting_dat[starting_dat$PLAYER_ID == 201939, ] # lebron 2544 and steph curry 201939
hist(steph_dat$FGA)
```

```{r}
luca_dat = starting_dat[starting_dat$PLAYER_ID == 1629029,] # Luca Donic 1629029
bam_dat = starting_dat[starting_dat$PLAYER_ID == 1628389,] # # Bam Adebayo 1628389
lebron_dat = starting_dat[starting_dat$PLAYER_ID == 2544,] # Lebron James 2544
steph_dat = starting_dat[starting_dat$PLAYER_ID == 201939, ] # steph curry 201939
# hist(lebron_dat$FGA)
# hist(rnbinom(100, max(lebron_dat$FGA), g))
# hist(steph_dat$FGA)
# hist(rnbinom(100, max(steph_dat$FGA), g))


a = 5
b = 5
par(mfrow=c(2,2))
hist(lebron_dat$FG_PCT)
hist(rbeta(100, a, b))
hist(steph_dat$FG_PCT)
hist(rbeta(100, a, b))
```

```{r}
player_FGA_stats <- starting_dat %>%
  group_by(PLAYER_NAME) %>%
  summarise(
    mean_FGA = round(mean(FGA, na.rm = TRUE), 2),
    var_FGA = round(var(FGA, na.rm = TRUE), 2),
    .groups = "drop"
  ) %>% drop_na() # dropping players who only started once!

sum(player_FGA_stats$var_FGA - player_FGA_stats$mean_FGA < -2, na.rm = TRUE)/nrow(player_FGA_stats)
# 53% have atleast 2 more variance than mean
# 14% have atleast 2 more mean than variance
# 33$ have variance within 2 of mean 
```

```{r}
starting_dat$MIN

starting_dat %>%
  mutate(
    MIN = str_replace(MIN, "([0-9]+)\\.[0-9]+:", "\\1:")
  )
```

